// <auto-generated />
using System;
using EF_26;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_26.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("OrderNumber")
                .StartsAt(100L)
                .IncrementsBy(2);

            modelBuilder.Entity("EF_26.Models.Car", b =>
                {
                    b.Property<string>("LicensePlate")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LicensePlate");

                    b.HasIndex("CarId")
                        .IsUnique()
                        .HasDatabaseName("CarIndex")
                        .HasFilter("[CARID] IS NOT NULL");

                    b.ToTable("Cars2");

                    b.HasData(
                        new
                        {
                            LicensePlate = "344",
                            CarId = 1,
                            Make = "china",
                            Model = "hundaye"
                        });
                });

            modelBuilder.Entity("EF_26.Models.CarRecordSales", b =>
                {
                    b.Property<int>("RecordSaleId")
                        .HasColumnType("int");

                    b.Property<string>("LicensePlate")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RecordSaleId", "LicensePlate");

                    b.HasIndex("LicensePlate");

                    b.ToTable("CarRecordSales");
                });

            modelBuilder.Entity("EF_26.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<long>("OrderNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("NEXT VALUE FOR OrderNumber");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EF_26.Models.OrderTesty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<long>("OrderNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("NEXT VALUE FOR OrderNumber");

                    b.HasKey("Id");

                    b.ToTable("OrderTesties");
                });

            modelBuilder.Entity("EF_26.Models.RecordSales", b =>
                {
                    b.Property<int>("RecordSaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordSaleId"));

                    b.Property<DateTime>("DateSold")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RecordSaleId");

                    b.ToTable("RecordSales");
                });

            modelBuilder.Entity("EF_26.Models.CarRecordSales", b =>
                {
                    b.HasOne("EF_26.Models.Car", "Cars2")
                        .WithMany("carRecordSales")
                        .HasForeignKey("LicensePlate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_26.Models.RecordSales", "RecordSales")
                        .WithMany("carRecordSales")
                        .HasForeignKey("RecordSaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cars2");

                    b.Navigation("RecordSales");
                });

            modelBuilder.Entity("EF_26.Models.Car", b =>
                {
                    b.Navigation("carRecordSales");
                });

            modelBuilder.Entity("EF_26.Models.RecordSales", b =>
                {
                    b.Navigation("carRecordSales");
                });
#pragma warning restore 612, 618
        }
    }
}
